/**
 * @fileoverview Dirty node tracking for AI regeneration
 * 
 * Tracks which nodes need AI regeneration and why
 * Enables incremental updates instead of full regeneration
 */

import * as NodeTypes from '../types/node.js';

// ==================== MARKING DIRTY ====================

/**
 * Mark a node as dirty (needs AI regeneration)
 * @param {NodeTypes.Node} node
 * @param {string} [reason] - Why it's dirty
 * @returns {NodeTypes.Node}
 */
export function markDirty(node, reason = 'content-changed') {
  return {
    ...node,
    metadata: {
      ...node.metadata,
      isDirty: true,
      modifiedAt: new Date().toISOString(),
    },
  };
}

/**
 * Mark a node as clean (regenerated by AI)
 * @param {NodeTypes.Node} node
 * @returns {NodeTypes.Node}
 */
export function markClean(node) {
  return {
    ...node,
    metadata: {
      ...node.metadata,
      isDirty: false,
      committedAt: new Date().toISOString(),
    },
  };
}

/**
 * Mark a node and all ancestors as dirty
 * @param {NodeTypes.Node} node
 * @param {Map<string, NodeTypes.Node>} nodeMap
 * @returns {string[]} - IDs of all marked dirty
 */
export function markDirtyWithAncestors(node, nodeMap) {
  const dirtyIds = [];
  let current = node;

  while (current) {
    dirtyIds.push(current.id);
    if (!current.hierarchy.parentId) break;
    current = nodeMap.get(current.hierarchy.parentId);
  }

  return dirtyIds;
}

/**
 * Mark a node and all descendants as dirty
 * @param {NodeTypes.Node} node
 * @param {Map<string, NodeTypes.Node>} nodeMap
 * @returns {string[]} - IDs of all marked dirty
 */
export function markDirtyWithDescendants(node, nodeMap) {
  const dirtyIds = [];
  const queue = [node];

  while (queue.length > 0) {
    const current = queue.shift();
    dirtyIds.push(current.id);

    for (const childId of current.hierarchy.childIds) {
      const child = nodeMap.get(childId);
      if (child) queue.push(child);
    }
  }

  return dirtyIds;
}

// ==================== FINDING DIRTY NODES ====================

/**
 * Find all dirty nodes in tree
 * @param {NodeTypes.Node} root
 * @param {Map<string, NodeTypes.Node>} nodeMap
 * @returns {NodeTypes.Node[]}
 */
export function findDirtyNodes(root, nodeMap) {
  const dirtyNodes = [];
  const queue = [root];
  const visited = new Set();

  while (queue.length > 0) {
    const current = queue.shift();

    if (visited.has(current.id)) continue;
    visited.add(current.id);

    if (current.metadata.isDirty) {
      dirtyNodes.push(current);
    }

    for (const childId of current.hierarchy.childIds) {
      const child = nodeMap.get(childId);
      if (child) queue.push(child);
    }
  }

  return dirtyNodes;
}

/**
 * Find all dirty root nodes (parents are clean)
 * These are the subtrees that need regeneration
 * 
 * @param {NodeTypes.Node} root
 * @param {Map<string, NodeTypes.Node>} nodeMap
 * @returns {NodeTypes.Node[]}
 */
export function findDirtyRoots(root, nodeMap) {
  const dirtyRoots = [];
  const allDirty = findDirtyNodes(root, nodeMap);

  for (const node of allDirty) {
    // Check if parent is dirty
    const parent = node.hierarchy.parentId
      ? nodeMap.get(node.hierarchy.parentId)
      : null;

    if (!parent || !parent.metadata.isDirty) {
      // This is a dirty root (parent is clean or no parent)
      dirtyRoots.push(node);
    }
  }
  return dirtyRoots;
}

/**
 * Count dirty nodes by type
 * @param {NodeTypes.Node[]} nodes
 * @returns {Object}
 */
export function countDirtyByType(nodes) {
  const counts = {};

  for (const node of nodes) {
    if (node.metadata.isDirty) {
      counts[node.type] = (counts[node.type] || 0) + 1;
    }
  }

  return counts;
}

// ==================== DIRTY SUBTREES ====================

/**
 * Build subtree information for dirty roots
 * Collects all affected nodes and sentences for AI processing
 * 
 * @param {NodeTypes.Node} dirtyRoot
 * @param {Map<string, NodeTypes.Node>} nodeMap
 * @returns {{rootId: string, level: number, descendants: NodeTypes.Node[]}}
 */
export function buildDirtySubtree(dirtyRoot, nodeMap) {
  const descendants = [];
  const queue = [...dirtyRoot.hierarchy.childIds];
  const visited = new Set([dirtyRoot.id]);

  while (queue.length > 0) {
    const nodeId = queue.shift();

    if (visited.has(nodeId)) continue;
    visited.add(nodeId);

    const node = nodeMap.get(nodeId);
    if (!node) continue;

    descendants.push(node);

    // Add children to queue
    for (const childId of node.hierarchy.childIds) {
      if (!visited.has(childId)) {
        queue.push(childId);
      }
    }
  }

  return {
    rootId: dirtyRoot.id,
    level: dirtyRoot.hierarchy.level,
    descendants,
  };
}

/**
 * Get all content nodes (sentences) in a dirty subtree
 * @param {{descendants: NodeTypes.Node[]}} subtree
 * @returns {NodeTypes.Node[]}
 */
export function getSubtreeContent(subtree) {
  return subtree.descendants.filter(
    n => n.hierarchy.role === 'content'
  );
}

/**
 * Get all grouping nodes in a dirty subtree
 * @param {{descendants: NodeTypes.Node[]}} subtree
 * @returns {NodeTypes.Node[]}
 */
export function getSubtreeGroups(subtree) {
  return subtree.descendants.filter(
    n => n.hierarchy.role === 'group'
  );
}

// ==================== CLEANUP ====================

/**
 * Mark all nodes as clean
 * After successful AI regeneration
 * 
 * @param {NodeTypes.Node[]} nodes
 * @returns {NodeTypes.Node[]}
 */
export function markAllClean(nodes) {
  return nodes.map(node => {
    if (node.metadata.isDirty) {
      return markClean(node);
    }
    return node;
  });
}

/**
 * Mark specific nodes as clean
 * @param {NodeTypes.Node[]} nodes
 * @param {string[]} nodeIds - IDs to clean
 * @returns {NodeTypes.Node[]}
 */
export function markNodesClean(nodes, nodeIds) {
  const cleanIds = new Set(nodeIds);

  return nodes.map(node => {
    if (cleanIds.has(node.id) && node.metadata.isDirty) {
      return markClean(node);
    }
    return node;
  });
}

/**
 * Clears all dirty flags from hierarchy
 * @param {Array} sentences - Sentences array
 * @returns {Array} Sentences with clean hierarchy
 */
export function clearDirtyFlags(sentences) {
    if (!sentences._hierarchyMeta) {
        return sentences;
    }

    const updated = [...sentences];
    const hierarchyMeta = { ...sentences._hierarchyMeta };

    /* delete hierarchyMeta.dirtyNodeIds;
    delete hierarchyMeta.dirtySentenceIds; */
    delete hierarchyMeta.dirtyNodeIds;
    delete hierarchyMeta.dirtySentenceIds;
    delete hierarchyMeta.dirtyLabelNodeIds;


    updated._hierarchyMeta = hierarchyMeta;

    console.log(`${LOG_PREFIX.PARSER} Cleared all dirty flags`);

    return updated;
}

// ==================== STATISTICS ====================

/**
 * Get dirty tracking statistics
 * @param {NodeTypes.Node[]} nodes
 * @returns {Object}
 */
export function getDirtyStats(nodes) {
  const dirtyCount = nodes.filter(n => n.metadata.isDirty).length;
  const cleanCount = nodes.length - dirtyCount;
  const dirtyByType = countDirtyByType(nodes);

  return {
    totalNodes: nodes.length,
    dirtyCount,
    cleanCount,
    dirtyPercentage: nodes.length > 0 ? (dirtyCount / nodes.length) * 100 : 0,
    dirtyByType,
  };
}

export default {
  // Marking
  markDirty,
  markClean,
  markDirtyWithAncestors,
  markDirtyWithDescendants,

  // Finding
  findDirtyNodes,
  findDirtyRoots,
  countDirtyByType,

  // Subtrees
  buildDirtySubtree,
  getSubtreeContent,
  getSubtreeGroups,

  // Cleanup
  markAllClean,
  markNodesClean,

  // Stats
  getDirtyStats,
};
